### ISSUE TITLE
Implementazione WebApi Gestione

### ISSUE THREAD

**Issue by AngeloDotNet** [AngeloDotNet/GestioneSagre#13]
- Configurazione iniziale
- Gestione Versione
- Gestione Logo (verrà creata una nuova issue)

**Comment by AngeloPirola** [comment]
Terminata implementazione WebApi Gestione Versione (commit defbfaa1d53cf926ff11e268aa5fa24d1685f85e)

**Comment by AngeloDotNet** [comment]
La configurazione iniziale dovrà essere implementata come WebApi Festa al posto di WebApi Strumenti

**Comment by AngeloPirola** [comment]
Terminata implementazione WebApi Gestione Festa (commit 7ab63d28e2c772d36fbd9753eb431e7268f9f0e1)
